services:
  - docker
jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build . -t shu-library
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag shu-library $DOCKER_USERNAME/shu-library
        - docker push $DOCKER_USERNAME/shu-library
